
#' Hours of Power Generated by Flubber
#'
#' This function determines the power level/total power generated by treated 
#' flubber rotating at a certain speed
#' @param mass mass of flubber (g)
#' @param viscosity viscosity of flubber (cP)
#' @param rotation rotation speed (m/2)
#' @param brightness brightness of light the flubber is exposed to (lumens)
#' @return power_lvl (W), total_power (J)
#' 


flubber_power = function(mass = 10, viscosity, rotation, brightness = 210) {
  power_lvl = (mass*brightness*rotation)/viscosity
  
  # takes 0.5 hours to burn through 1g of flubber, sample = 5 hours
  # 3600 s/hr
  total_power = power_lvl*3600*5
  
  return(list(power_lvl, total_power))
}