
#' Hours of Power Generated by Flubber
#'
#' This function determines the power level/hours of power generated by treated 
#' flubber rotating at a certain speed
#' @param mass mass of flubber (g)
#' @param viscosity viscosity of flubber (cP)
#' @param rotation rotation speed (m/2)
#' @param brightness brightness of light the flubber is exposed to (lumens)
#' @return power (W), timeframe of power (hours)
#' 


flubber_power = function(viscosity, rotation, mass = 150, brightness = 410) {
  power = ((mass/viscosity)^brightness)/rotation
  
  hours_power = power*3600
  
  return(list(power, hours_power))
}